# SuperBench Config
#
# Azure HB120rs_v4/HX
# reference: https://learn.microsoft.com/en-us/azure/virtual-machines/hbv4-series
# reference: https://learn.microsoft.com/en-us/azure/virtual-machines/hx-series

version: v0.6
superbench:
  enable: null
  monitor:
    enable: true
    sample_duration: 1
    sample_interval: 10
  benchmarks:
    ib-loopback:
      enable: false
      modes:
        - name: local
          proc_num: 1
          prefix: PROC_RANK={proc_rank} IB_DEVICES=0 NUMA_NODES=0
          parallel: yes
        - name: local
          proc_num: 1
          prefix: PROC_RANK={proc_rank} IB_DEVICES=0 NUMA_NODES=0
          parallel: yes
        parameters:
          bin_dir:
            - /usr/bin
    disk-benchmark:
      enable: false
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        block_devices:
          - /dev/nvme0n1
    cpu-memory-bw-latency:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        tests:
          - bandwidth_matrix
          - latency_matrix
          - max_bandwidth
    cpu-hpl:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        coreCount: 88
        cpu_arch: zen4
        blockSize: 384
        blocks: 1
        problemSize: 384000
    cpu-stream:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        cores: 0 8 16 24 32 38 44 52 60 68 76 82 88 96 104 112 120 126 132 140 148 156 164 170
        cpu_arch: zen4
    ib-traffic:
      enable: false
      modes:
        - name: mpi
          proc_num: 8
      parameters:
        msg_size: 8388608
        ib_dev: mlx5_$LOCAL_RANK
        gpu_dev: $LOCAL_RANK
        numa_dev: $((LOCAL_RANK/2))
    tcp-connectivity:
      enable: false
      modes:
        - name: local
          parallel: no
      parameters:
        port: 22
