version: 2
updates:
  # enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
    assignees:
      - "guoshzhao"
  # enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
    assignees:
      - "abuccts"
