codecov:
  require_ci_to_pass: yes

flag_management:
  default_rules:
    carryforward: true
    paths:
      - superbench/

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        flags:
          - cpu-unit-test
          - cuda-unit-test
    patch:
      default:
        target: 80%
        threshold: 1%
        flags:
          - cpu-unit-test
          - cuda-unit-test
