- name: Fetch Results
  hosts: all
  gather_facts: true
  vars:
    workspace: '{{ ansible_user_dir }}/sb-workspace'
  tasks:
    - name: Synchronize Output Directory
      ansible.posix.synchronize:
        mode: pull
        src: '{{ sb_output_dir if sb_output_dir.startswith("/") else workspace + "/" + sb_output_dir  }}/'
        dest: '{{ absolute_output_dir }}/nodes/{{ ansible_hostname }}'
        rsync_opts:
          - --exclude=nodes
