name: GitHub Pages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docs-build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test docs build
        run: |
          cd website
          npm ci
          npm run build
  docs-publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Publish to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: abuccts
          CURRENT_BRANCH: main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd website
          npm ci
          npm run deploy
