name: Lint

on:
  pull_request:
    branches:
    - main
    - release/*

jobs:
  spelling:
    name: Spelling check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        curl -fsSL --retry 3 -o /tmp/misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz
        tar -xzf /tmp/misspell.tar.gz -C /tmp
        sudo install /tmp/misspell /bin/misspell
    - name: Check spelling
      run: |
        misspell -error .
  cpp:
    name: CPP code lint
    runs-on: ubuntu-latest
    steps:
    - name: Install clang-format-14
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-14
        sudo ln -sf /usr/bin/clang-format-14 /usr/bin/clang-format
    - name: Checkout
      uses: actions/checkout@v2
    - name: Echo clang-format version
      run: |
        clang-format --version
    - name: Lint
      run: |
        make cpplint
